### ISSUE TITLE
New progress bar might be good

### ISSUE THREAD

**Issue by Nullf0x** [CrackerHacker00/BruteDev#3]
Hi, CH,
   I made this piece of code to make a progress bar(really simple). I was wondering whether you would like to add this while loading new menus :
  
-------------------------------
echo -ne '----                   (33%)\r'
sleep 1
echo -ne '--------           (66%)\r'
sleep 1
echo -ne '------------  (100%)\r'
echo -ne '\n'
---------------------------------

Thanks,
    Nullf0x

**Comment by CrackerHacker00** [comment]
I'll add a progress bar, sure. But it will need more to code in than that. I'll do some research and push when I get something.

**Comment by Nullf0x** [comment]
thanks. Just veiw the Brutedev projects site here : http://nullf0x.github.io/brutedev.github.io
