### ISSUE TITLE
New dialouge boxes might be good

### ISSUE THREAD

**Issue by Nullf0x** [CrackerHacker00/BruteDev#4]
Hi, CH,

   I thought making good dialouge boxes, for displatying errors and other things like that will be good, so here's the code i made for it:

------------------------------------------
dialog --title "ERROR" --msgbox 'What in the world is the error!' 6 20
------------------------------------------

But for this you need to install the pacckage :

sudo apt-get update
sudo apt-get install dialog

Thanks,
   Nullf0x

**Comment by CrackerHacker00** [comment]
Unfortunately, adding errors is much more difficult than you think. However, I can set an error when the user presses CTRL + C. That's just about it for now.

**Comment by Nullf0x** [comment]
thanks.
